# Generated by Django 2.2.6 on 2019-10-21 04:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('search', '0007_auto_20191020_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='active',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='author',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='body',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='thumb',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='title',
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='metadata',
            name='x_coord',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='y_coord',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='z_coord',
            field=models.IntegerField(max_length=10),
        ),
    ]
